apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: custom-runner
spec:
  replicas: 1
  template:
    spec:
      repository: mihir-hadavani-inventyv/k8s-yml
      labels:
        - custom-runner
      hostAliases:
        - ip: "192.168.230.128"
          hostnames:
            - "mihir.harbor.com" 

