apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: custom-runner
spec:
  replicas: 1
  template:
    spec:
      repository: mihir-hadavani-inventyv/k8s-yml  # Your GitHub repo
      labels:
        - custom-runner  # Label for workflow targeting
      hostAliases:
        - ip: "192.168.230.128"  # Your Harbor registry IP
          hostnames:
            - "mihir.harbor.com"  # Hostname for Harbor
      volumes:
        - name: docker-config
          configMap:
            name: docker-insecure-config
      containers:
        - name: runner
          image: summerwind/actions-runner:latest
          volumeMounts:
            - name: docker-config
              mountPath: /etc/docker/daemon.json
              subPath: daemon.json
      #dockerdWithinRunnerContainer: true
       # Mount only the daemon.json file
      # Optional: Uncomment if you need to pin to a specific node
      # nodeSelector:
      #   kubernetes.io/hostname: <your-node-name>
