---

- name: User Mgm
  hosts: all
  
  tasks:
    - name: User creation
      user:
        name: test1
        comment: adding a user for QA team
        shell: /bin/bash
        password: "{{ '2107' | password_hash('sha512') }}"
        groups: qa
        state: present
      become: true
        